baseUrl = "https://phasewalk1.github.io/"
languageCode = 'en-us'
title = 'deepmeow'
theme = 'brutalist-minimalist'
relativeURLs = true

[markup]
[markup.highlight]
noClasses = false
[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 3


[params]

# --- Site config ---------------------------------

subtitle = 'a little bit of everything'
siteBasename = "phasewalk1's deepmeow"
copyright = "M E Leypold"
copyrightYear = "2021-2022"             # for site in case there is no page date, not yet implemented

# --- Style tweaking ------------------------------

bloglistLength = 3 # number of blog posts to turn up at front page, 0 for
# none.

highlightStyle = 'emacs' # builtin styles: emacs, pygment. Empty for none.
enableKatex = true       # If off, math is rendered as plain text (verbatim)

# Only set the following parameters if you create
# the css files referenced in them.
#
styleParametersCSS = 'css/style-parameters.css'
styleTweaksCSS = 'css/style-tweaks.css'
# fontSettingsCSS         = 'css/font-settings.css'

# Fall back to more minimalism
styleMinimalistOnly = false
noStylingAtAll = false      # we use that to see how this might render in text mode

# Overriding responsiveness
# responsivenessLimitsCSS = 'css/NONE.css'
# limitCompactMenu      = 55
# limitHamburgerMenu    = 40	    
# limitCompactLayout    = 30	    
# limitNarrowLayout     = 25	  
# limitVeryNarrowLayout = 17

averageCharWidth = 0.7

[deployment]

testing = "/srv/http/bm-testing"
production = "rsync://web-op@www.glitzersachen.de:/var/www/html/brutalist-minimalist"
